# Generated by Django 3.0 on 2022-02-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gen', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=11)),
                ('fees', models.IntegerField()),
                ('about', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
