# Generated by Django 3.0 on 2022-02-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
                ('duration', models.CharField(max_length=15)),
                ('trainer', models.CharField(max_length=20)),
            ],
        ),
    ]
